name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: superuser
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
    unit-testing:
        name: Unit Testing
        services:
          mongo-db:
            image: siddharth67/mongo-db:non-prod
            ports:
              - 27017:27017
        env:
          MONGO_URI: 'mongodb://localhost:27017/superData'
          MONGO_USERNAME: non-prod-user
          MONGO_PASSWORD: non-prod-password
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4
          - name: Setup NodeJS Version
            uses: actions/setup-node@v4
            with:
              node-version: 20
          - name: Cache NPM dependencies
            uses: actions/cache@v3
            with:
              path: node_modules
              key: ${{ runner.os }}-node-moduules-${{ hashFiles('package-lock.json') }}
          - name: Install Dependencies
            run: npm install
          - name: Unit Testing
            run: npm test
          - name: Archive Test Result
            if: always()      #added
            uses: actions/upload-artifact@v4
            with:
              name: Mocha-Test-Result
              path: test-results.xml
    code-coverage:
        name: Code Coverage
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4
          - name: Setup NodeJS Version
            uses: actions/setup-node@v4
            with:
              node-version: 18
          - name: Cache NPM dependencies
            uses: actions/cache@v3
            with:
              path: node_modules
              key: ${{ runner.os }}-node-moduules-${{ hashFiles('package-lock.json') }}
          - name: Install Dependencies
            run: npm install
          - name: Code-coverage
            continue-on-error: true
            run: npm run coverage
          - name: Code-Coverage-Result
            if: always()      #added
            uses: actions/upload-artifact@v4
            with:
              name: Code-Coverage-Result
              path: coverage
              retention-days: 5       
    docker:
      name: Containerization
      needs: [unit-testing,code-coverage]
      permissions: 
        packages: write
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        - name: Docker Login
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Docker Build to test
          uses: docker/build-push-action@v6
          with:
            push: false
            tags: ghcr.io/${{ github.actor }}/solar-system:${{ github.sha }}
        - name: Docker Image Testing
          run: |
            docker images
            docker run --name solar-syste-app -d \
              -p 3000:3000 \
              -e MONGO_URI=$MONGO_URI \
              -e MONGO_USERNAME=$MONGO_USERNAME \
              -e MONGO_PASSWORD=$MONGO_PASSWORD \
              ghcr.io/${{ github.actor }}/solar-system:${{ github.sha }}
          
            echo Testing Image URL using wget
            wget =q -O - 127.0.0.1:3000/live | grep live
        - name: Docker push
          uses: docker/build-push-action@v6
          with: 
            push: true
            tags: ghcr.io/${{ github.actor }}/solar-system:${{ github.sha }}